name: 'snail_data_solutions'
version: '1.0.0'
config-version: 2

profile: 'snail_data_solutions'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  snail_data_solutions:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
